<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: yii.php 1901 2010-03-14 03:51:17Z qiang.xue $
*/
return array (
    'Home' => 'منزل',
    'About' => 'حول',
    'Contact' => 'اتصل',
    'Sample Controls' => 'التحكم عينة',
    'Login' => 'دخول',
    'Logout' => 'خروج',
);
